name: kidtopia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  cached_network_image: ^3.3.1

  flutter_localizations:
    sdk: flutter

  intl: any

  flutter_bloc: ^9.1.1
  get_it: ^9.1.0
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

  supabase_flutter: ^2.3.0
  crypto: ^3.0.2
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_crashlytics: ^5.0.6
  
  
  equatable: ^2.0.5
  
  # Background Jobs
  workmanager: ^0.9.0
  # Local Notifications
  flutter_local_notifications: ^19.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^0.3.1
  integration_test:
    sdk: flutter

 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/images/
    - assets/seeds/categories.json
    - assets/seeds/questions.json
    - assets/seeds/answers.json


