// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWD1kTqR4s9o-BhgiG-BsiJ7QYrVY3UE',
    appId: '1:793550015462:web:10d1441e774de0aa026427',
    messagingSenderId: '793550015462',
    projectId: 'kidtopia-8dffe',
    authDomain: 'kidtopia-8dffe.firebaseapp.com',
    storageBucket: 'kidtopia-8dffe.firebasestorage.app',
    measurementId: 'G-PTXDKJZH9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMp-uk51FzIf65yMjhNCjJlJks1yRuas',
    appId: '1:793550015462:android:e41fe2b09327aa8d026427',
    messagingSenderId: '793550015462',
    projectId: 'kidtopia-8dffe',
    storageBucket: 'kidtopia-8dffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVdsA2_gjS3FEqkqXKISOwFY7nIHegr0',
    appId: '1:793550015462:ios:c88c66378bd60c96026427',
    messagingSenderId: '793550015462',
    projectId: 'kidtopia-8dffe',
    storageBucket: 'kidtopia-8dffe.firebasestorage.app',
    iosBundleId: 'com.example.kidtopiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMVdsA2_gjS3FEqkqXKISOwFY7nIHegr0',
    appId: '1:793550015462:ios:c88c66378bd60c96026427',
    messagingSenderId: '793550015462',
    projectId: 'kidtopia-8dffe',
    storageBucket: 'kidtopia-8dffe.firebasestorage.app',
    iosBundleId: 'com.example.kidtopiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWD1kTqR4s9o-BhgiG-BsiJ7QYrVY3UE',
    appId: '1:793550015462:web:03ef2d28e19ea3d0026427',
    messagingSenderId: '793550015462',
    projectId: 'kidtopia-8dffe',
    authDomain: 'kidtopia-8dffe.firebaseapp.com',
    storageBucket: 'kidtopia-8dffe.firebasestorage.app',
    measurementId: 'G-8BZHV525KS',
  );
}
